language: generic

dist: xenial

sudo: true

branches:
  except:
    - release

branches:
  only:
    - master
    - develop

before_install:
  - sudo curl -sL https://deb.nodesource.com/setup_6.x | sudo bash -
  - sudo apt-get install -y devscripts fakeroot debhelper pkg-config alien rpm dh-make nodejs

script:
  - echo $TRAVIS_BUILD_NUMBER > RELEASE
  - make deps
  - make build

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ -n "$BT_APIUSER" ]; then make bintray APIUSER=${BT_APIUSER} APIKEY=${BT_APIKEY}; fi;
