language: node_js

dist: trusty

sudo: true

branches:
  except:
    - release

branches:
  only:
    - master
    - develop

node_js:
  - node

before_install:
  - sudo apt-get update || true

addons:
  apt:
    packages:
    - devscripts
    - fakeroot
    - debhelper
    - pkg-config
    - alien
    - rpm
    - dh-make

script:
  - make deps
  - make build

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ -n "$BT_APIUSER" ]; then make bintray APIUSER=${BT_APIUSER} APIKEY=${BT_APIKEY}; fi;
